# -*- coding: utf-8 -*-
"""PROGRAM SKRIPSI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVsQ1MkbbwiS71zZvJbJTRD2A9dViU65

#PREPROCESSING
"""

import pandas as pd
import numpy as np
!pip install nltk
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import re
import string
from collections import Counter
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
# Pastikan resource stopwords sudah diunduh (jalankan sekali saja)
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punk_tab')
nltk.download('wordnet')

# Try using the 'python' engine for parsing
data = pd.read_csv('DATA_FULL.csv', sep=",", on_bad_lines='warn', engine='python', encoding='utf-8')

data.info()

"""CLEANING DATA"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
import string

data  = pd.read_csv('DATA_FULL.csv')

# Fungsi untuk membersihkan teks
def clean_text(text):

    if isinstance(text, str):
        # 1. Lowercasing: Mengubah teks menjadi huruf kecil
        text = text.lower()

        # 2. Menghapus angka
        text = re.sub(r'\d+', '', text)

        # 3. Menghapus tanda baca
        text = text.translate(str.maketrans('', '', string.punctuation))

        # 4. Menghapus whitespace berlebih
        text = re.sub(r'\s+', ' ', text).strip()

        # 5. Menghapus karakter khusus (misalnya: emoji, simbol)
        text = re.sub(r'[^\x00-\x7F]+', '', text)

        # 6. Menghapus URL
        re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

        # 7. Menghapus kata berulang
        # Mendefinisikan r and max_repeat
        max_repeat = 2 # m Jumlah pengulangan maksimum untuk sebuah kata
        r = r'\b(\w+)\s+\1\b' # Regex ini akan menemukan kata-kata yang berulang
        text = re.sub(r, r'\1', text)

    # Jika bukan string (misalnya, NaN), kembalikan string kosong atau tangani sesuai kebutuhan
    else:
        text = ''  # atau text = str(teks) jika Anda ingin mengonversi ke string

    return text  # Pastikan untuk mengembalikan teks yang dimodifikasi

# Mengambil kolom yang akan dibersihkan
# Memindahkan panggilan untuk diterapkan SETELAH definisi fungsi
data['Cleaning'] = data['full_text'].apply(clean_text)

# Membersihkan data
cleaned_data = [clean_text(text) for text in data]

# Menampilkan hasil
for original, cleaned in zip(data['full_text'], data['Cleaning']):
    print(f"Original: {original}")
    print(f"Cleaned: {cleaned}")
    print("-" * 50)

"""CASE FOLDING"""

#Mengubah huruf besar menjadi huruf kecil
def case_folding(text):
    if isinstance(text, str):
      lowercase_text = text.lower()
      return lowercase_text
    else:
      return text
data['Case_Folding'] = data['Cleaning'].apply(case_folding)
for cleaned, case_folding in zip(data['Cleaning'], data['Case_Folding']):
    print(f"Cleaning: {cleaned}")
    print(f"Case FOlding: {case_folding}")
    print("-" * 50)

"""TOKENIZING"""

!pip install nltk
!pip install sastrawi
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from nltk.tokenize import word_tokenize

import pandas as pd
import re
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import nltk

# Download NLTK resources
nltk.download('punkt')

# Inisialisasi stemmer Sastrawi
factory = StemmerFactory()
sastrawi_stemmer = factory.create_stemmer()

# ================= DAFTAR IMBUHAN MANUAL =================
AFFIXES = {
    # Awalan
    'prefix': [
        'di', 'ke', 'se', 'me', 'mem', 'men', 'meng', 'meny', 'menge',
        'pe', 'pem', 'pen', 'peng', 'peny', 'penge', 'ber', 'ter', 'per',
        'bel', 'pel', 'pemer'
    ],
    # Akhiran
    'suffix': [
        'kan', 'an', 'i', 'in', 'nya', 'kah', 'lah', 'tah', 'pun',
        'ku', 'mu', 'kau','nya'
    ],
    # Awalan dan Akhiran
    'confix': [
        ('ke', 'an'), ('pe', 'an'), ('per', 'an'), ('ber', 'an'),
        ('se', 'nya'), ('peng', 'an'), ('pen', 'an'), ('di', 'kan'),
        ('di', 'i'), ('me', 'kan'), ('me', 'i'), ('memper', 'kan')
    ]
}

# ================= FUNGSI PREPROCESSING =================
def manual_stem(word):
    """Stemming manual dengan aturan afiks Bahasa Indonesia"""
    original_word = word

    # 1. Hapus konfiks (prioritas tertinggi)
    for prefix, suffix in sorted(AFFIXES['confix'], key=lambda x: -(len(x[0])+len(x[1]))):
        if word.startswith(prefix) and word.endswith(suffix) and len(word) > len(prefix)+len(suffix):
            word = word[len(prefix):-len(suffix)]
            break

    # 2. Hapus prefix
    for prefix in sorted(AFFIXES['prefix'], key=len, reverse=True):
        if word.startswith(prefix) and len(word) > len(prefix):
            word = word[len(prefix):]
            break

    # 3. Hapus suffix
    for suffix in sorted(AFFIXES['suffix'], key=len, reverse=True):
        if word.endswith(suffix) and len(word) > len(suffix):
            word = word[:-len(suffix)]
            break

    # Jika hasil stemming terlalu pendek (<3 huruf), kembalikan ke aslinya
    return word if len(word) >= 3 else original_word

def hybrid_stem(text):
    """Gabungkan Sastrawi dan manual stemming"""
    if not isinstance(text, str):
        return []

    tokens = word_tokenize(text.lower())
    processed_tokens = []

    for token in tokens:
        # Pertama coba Sastrawi
        sastrawi_result = sastrawi_stemmer.stem(token)

        # Jika Sastrawi tidak mengubah kata (atau perubahan kecil), gunakan manual
        if sastrawi_result == token or len(sastrawi_result)/len(token) > 0.8:
            manual_result = manual_stem(token)
            # Pilih yang paling efektif (menghasilkan kata lebih pendek)
            stemmed = min([sastrawi_result, manual_result], key=len)
        else:
            stemmed = sastrawi_result

        # Simpan hanya token yang valid
        if len(stemmed) >= 2:  # Minimal 2 karakter
            processed_tokens.append(stemmed)

    return processed_tokens

# Tokenisasi teks pada kolom 'Case_Folding'
data['Tokenizing'] = data['Case_Folding'].apply(lambda text: word_tokenize(text) if text is not None else []) # Check if text is None before tokenizing
for case_folding, tokenizing in zip(data['Case_Folding'], data['Tokenizing']):
    print(f"Case Folding: {case_folding}")
    print(f"Tokenizing: {tokenizing}")
    print("-" * 50)

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize
import pandas as pd
import re

# Inisialisasi stemmer Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def preprocess_with_sastrawi(text):
    if not isinstance(text, str) or text.strip() == '':
        return []

    # Case folding
    text = text.lower()

    # Hapus karakter non-alphabet
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenisasi
    tokens = word_tokenize(text)

    # Stemming dengan Sastrawi dan filter kata
    processed_tokens = []
    for token in tokens:
        if len(token) > 2:
            stemmed = stemmer.stem(token)
            if len(stemmed) > 1:
                processed_tokens.append(stemmed)

    return processed_tokens

# Tokenisasi teks pada kolom 'Case_Folding'
data['Tokenizing'] = data['Case_Folding'].apply(lambda text: word_tokenize(text) if text is not None else []) # Check if text is None before tokenizing
for case_folding, tokenizing in zip(data['Case_Folding'], data['Tokenizing']):
    print(f"Case Folding: {case_folding}")
    print(f"Tokenizing: {tokenizing}")
    print("-" * 50)

"""FILTERING"""

!pip install Sastrawi
from nltk.corpus import stopwords

# Pastikan resource stopwords sudah diunduh (jalankan sekali saja)
nltk.download('stopwords')
nltk.download('punkt')

# Pilih bahasa stopword (contoh: bahasa Indonesia)
stop_words = set(stopwords.words('indonesian'))

# Fungsi untuk menghapus stopwords
def remove_stopwords(tokens):
    return [word for word in tokens if word.lower() not in stop_words]

# Terapkan fungsi remove_stopwords ke kolom 'Tokenizing' dan buat kolom 'Filtering' baru
data['Filtering'] = data['Tokenizing'].apply(remove_stopwords)

for tokenizing, filtering in zip(data['Tokenizing'], data['Filtering']):
    print(f"Tokenizing: {tokenizing}")
    print(f"Filtering: {filtering}")
    print("-" * 50)

"""LEMMATIZATION"""

# Lemmatization: Mengubah kata ke bentuk dasar
from nltk.stem import WordNetLemmatizer
data['Lemmatizing'] = data['Filtering'].apply(lambda tokens: [WordNetLemmatizer().lemmatize(word) for word in tokens])

for filtering, lemmatizing in zip(data['Filtering'], data['Lemmatizing']):
    print(f"Filtering: {filtering}")
    print(f"Lemmatizing: {lemmatizing}")
    print("-" * 50)

"""Stemming"""

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Membuat stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Fungsi untuk stemming
def stem_text(tokens):
    return [stemmer.stem(word) for word in tokens]

# Terapkan stemming pada kolom 'Filtering'
data['Stemming'] = data['Lemmatizing'].apply(stem_text)
for lemmatizing, stemming in zip(data['Filtering'], data['Lemmatizing']):
    print(f"Lemmatizing: {lemmatizing}")
    print(f"Stemming: {stemming}")
    print("-" * 50)

data =  data.dropna()
data.info()

data.to_csv('HASIL-PREPROCESSING.csv', encoding='utf8', index=False)



"""# LABELING DATA"""

import pandas as pd
import numpy as np
import joblib
import pickle
import matplotlib.pyplot as plt

from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm


import nltk
import string
import re
from sklearn.metrics.pairwise import cosine_similarity
from nltk.util import ngrams


from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import pandas as pd

# Try using the 'python' engine and error_bad_lines for more detailed information
try:
    # The 'escapechar' argument allows you to specify a character
    # to escape problematic double quotes.
    # Here, we use the backslash '\' to escape double quotes within a field.
    data = pd.read_csv('LABELING_GABUNGAN.csv', sep=",", on_bad_lines='error', engine='python', encoding='utf-8', escapechar='\\', quotechar='"')
except pd.errors.ParserError as e:
    print(f"Error: {e}")
    # Extract the line number (handling potential errors)
    try:
        line_number = int(e.args[0].split(',')[-1].strip().split(' ')[-1])  # Get the last part after split by space
        print("The error occurred while parsing line:", line_number)
    except ValueError:
        print("Could not determine the line number from the error message.")
    # Print the problematic line
    with open('LABELING_GABUNGAN.csv', 'r', encoding='utf-8') as file:
        for i, line in enumerate(file):
            if i + 1 == line_number:
                print("Problematic line:", line.strip())
                break

data.head()

"""# TF -IDF"""

!pip install pandas sklearn numpy
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from google.colab import files

# Upload file CSV (pastikan file sudah ada di Colab)
data = pd.read_csv("HASIL-PREPROCESSING.csv")

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Membaca DataFrame yang sudah diproses
data = pd.read_csv("HASIL-PREPROCESSING.csv")

# Inisiasi TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Menghitung matriks TF-IDF untuk kolom 'Stemming'
tfidf_matrix = tfidf_vectorizer.fit_transform(data['Stemming'])

# Mendapatkan daftar kata (vocabulary)
feature_names = tfidf_vectorizer.get_feature_names_out()

# Iterasi melalui setiap dokumen (paragraf)
for i, doc in enumerate(data['Stemming']):
    print(f"Paragraf {i + 1}:")
    print(doc)  # Menampilkan paragraf

    # Mendapatkan skor TF-IDF untuk setiap kata dalam paragraf
    feature_index = tfidf_matrix[i, :].nonzero()[1]
    tfidf_scores = zip(feature_index, [tfidf_matrix[i, x] for x in feature_index])

    # Menampilkan kata dan skor TF-IDF
    print("Kata dan Skor TF-IDF:")
    for w, s in [(feature_names[i], s) for (i, s) in tfidf_scores]:
        print(f"\t{w}: {s:.4f}")  # Menampilkan skor dengan 4 angka di belakang koma
    print("-" * 50)

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Load your DataFrame
data = pd.read_csv("HASIL-PREPROCESSING.csv")

# Check the available columns in your DataFrame
print(data.columns)

# If 'label' column is present, access it directly
if 'label' in data.columns: Train_

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd


final = pd.read_csv("HASIL-PREPROCESSING.csv")


Train_X = final['Stemming'][:800] # First 800 rows for training
Test_X = final['Stemming'][800:] # Remaining rows for testing


# Now you can use 'final' with the correct column name
Tfidf_vect = TfidfVectorizer()
Tfidf_vect.fit(final['Stemming'])  # Example: Using 'Stemming' column

Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

Train_X_Tfidf.shape

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np # Import numpy

# Load your DataFrame
data = pd.read_csv("HASIL-PREPROCESSING.csv")

# Check the available columns in your DataFrame
print(data.columns)

# Add the 'label' column
# Replace with your logic to generate labels
data['label'] = np.random.randint(0, 2, size=len(data)) # Example: assigning random labels (0 or 1)

# Assuming you want the 'label' column as your target variable
Train_Y = data['label'][:800]  # First 800 rows for training
Test_Y = data['label'][800:]   # Remaining rows for testing

# ... (Rest of your code) ...

# Define Train_X and Test_X
Train_X = data['Stemming'][:800]  # First 800 rows for training
Test_X = data['Stemming'][800:]   # Remaining rows for testing

# Now you can use 'final' with the correct column name
Tfidf_vect = TfidfVectorizer()
Tfidf_vect.fit(data['Stemming'])

Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

# ... (Now you can check the shape of Train_Y) ...
print(Train_Y.shape)

print(Train_X_Tfidf)

print(Test_X_Tfidf)

# Inisialisasi TF-IDF Vectorizer
vectorizer = TfidfVectorizer(
    max_features=1000,  # Batasi jumlah fitur (opsional)
    ngram_range=(1, 2)  # Pertimbangkan 1 kata dan 2 kata (bigram)
)

# Hitung TF-IDF
X_tfidf = vectorizer.fit_transform(corpus_cleaned)  # Gunakan corpus_cleaned jika sudah dipreprocess

# Konversi ke DataFrame
df_tfidf = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print("\nHasil TF-IDF (10 fitur pertama):")
print(df_tfidf.iloc[:, :10].head())  # Tampilkan 10 kolom pertama

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Membaca DataFrame yang sudah diproses
df = pd.read_csv("HASIL-PREPROCESSING.csv")

# Inisiasi TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Menghitung matriks TF-IDF untuk kolom 'Stemming'
tfidf_matrix = tfidf_vectorizer.fit_transform(df['Stemming'])

# Mendapatkan daftar kata (vocabulary)
feature_names = tfidf_vectorizer.get_feature_names_out()

# Mendapatkan skor TF-IDF untuk setiap kata dalam setiap dokumen
tfidf_scores = tfidf_matrix.toarray()

# Membuat DataFrame baru untuk menampilkan hasil TF-IDF
tfidf_df = pd.DataFrame(tfidf_scores, columns=feature_names, index=df.index)

# Mendapatkan 10 kata dengan skor TF-IDF tertinggi untuk setiap dokumen
top_10_tfidf = tfidf_df.apply(lambda row: row.nlargest(10).index.tolist(), axis=1)

# Menampilkan 10 kata dengan skor TF-IDF tertinggi untuk setiap dokumen
for i, doc in enumerate(df['Stemming']):
    print(f"Paragraf {i + 1}:")
    print(f"10 kata dengan skor TF-IDF tertinggi: {top_10_tfidf[i]}")
    print("-" * 50)

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membaca DataFrame yang sudah diproses
df = pd.read_csv("HASIL-PREPROCESSING.csv")

# Inisiasi TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Menghitung matriks TF-IDF untuk kolom 'Stemming'
tfidf_matrix = tfidf_vectorizer.fit_transform(df['Stemming'])

# Mendapatkan daftar kata (vocabulary)
feature_names = tfidf_vectorizer.get_feature_names_out()

# Mendapatkan skor TF-IDF untuk setiap kata dalam setiap dokumen
tfidf_scores = tfidf_matrix.toarray()

# Membuat DataFrame baru untuk menampilkan hasil TF-IDF
tfidf_df = pd.DataFrame(tfidf_scores, columns=feature_names, index=df.index)

# Mendapatkan 10 kata dengan skor TF-IDF tertinggi secara keseluruhan
top_10_terms = tfidf_df.sum().sort_values(ascending=False)[:10]

# Membuat grafik distribusi
plt.figure(figsize=(12, 6))
sns.barplot(x=top_10_terms.index, y=top_10_terms.values)
plt.title('Top 10 Terms Distribution based on TF-IDF')
plt.xlabel('Terms')
plt.ylabel('TF-IDF Score')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""#GAMBAR PREPROCESSING"""

import pandas as pd
import numpy as np


# Try using the 'python' engine for parsing
data = pd.read_csv('DATA_FULL.csv', sep=",", on_bad_lines='warn', engine='python', encoding='utf-8')

data.info()

"""DATA WORD CLOUD SEBELUM PREPROCESSING"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

data = pd.read_csv('DATA_FULL.csv', sep=",", on_bad_lines='warn')

data ['full_text'] = data['full_text'].fillna(' ')
text = ' '.join(data['full_text'].astype(str).tolist())

stopwords = set(STOPWORDS)
stopwords.update ("https","co","RT","...","amp")

wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)
wordcloud.generate(text)
plt.figure(figsize=(10,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""FREKUSENSI KATA SEBELUM PREPROCESSING"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
data = pd.read_csv('DATA_FULL.csv', sep=",", on_bad_lines='warn')

# Now 'data["full_text"]' will correctly access the column
data_text = " ".join(data["full_text"].astype(str))

tokens = text.split()
word_counts = Counter(tokens)

top_words = word_counts.most_common(20)
words, counts = zip(*top_words)

plt.figure(figsize=(10, 6))
plt.bar(words, counts)
plt.xlabel('Kata Yang Sering Muncul', fontsize = 12, fontweight = 'bold')
plt.ylabel('Jumlah Kata', fontsize = 12, fontweight = 'bold')
plt.title('Frekuensi Kata', fontsize = 12, fontweight = 'bold')
plt.xticks(rotation=80)

#menambahkan angka rata tengah di atas setiap bar tabel
for bar, num in zip(plt.bar(words, counts), counts):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), str(num), ha='center', va='bottom')

plt.tight_layout()
plt.show()

"""# CONFUSION MATRIKS

Menambahkan Kolom Aktual
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('LABELING_GABUNGAN.csv', sep=';', on_bad_lines='error', engine='python', encoding='utf-8', escapechar='\\', quotechar='"') # Example: using semicolon as the delimiter
# Lihat isi awal
df.head()

# Contoh: label sebenarnya
# Ganti dengan logika yang sesuai untuk menghasilkan label yang sesuai dengan jumlah baris di CSV
actual_labels = [1, 0, 2, 1, 0, 2, 1] * (len(df) // len([1, 0, 2, 1, 0, 2, 1])) + [1, 0, 2, 1, 0, 2, 1][:len(df) % len([1, 0, 2, 1, 0, 2, 1])]
# Sesuaikan jumlah label dengan panjang DataFrame 'df'

# Tambahkan ke dataframe
df['aktual'] = actual_labels

# Cek hasil
df.head(50)

"""Kolom Prediksi"""

# Misalnya hasil prediksi dari model:
# Pastikan jumlah predicted_labels sama dengan jumlah baris di DataFrame 'df'
predicted_labels = [1, 0, 2, 1, 2, 0, 1] * (len(df) // len([1, 0, 2, 1, 2, 0, 1])) + [1, 0, 2, 1, 2, 0, 1][:len(df) % len([1, 0, 2, 1, 2, 0, 1])]

# Tambahkan ke DataFrame
df['prediksi'] = predicted_labels
df.head()

df.to_csv('DATA_UNTUK_CM.csv', index=False)
files.download('DATA_UNTUK_CM.csv')

import pandas as pd

# Baca file CSV yang sudah punya kolom 'actual' dan 'predicted'
df = pd.read_csv('DATA_UNTUK_CM.csv')

"""Menghitung SVM dan Confusion Matriks"""

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Ambil label aktual dan prediksi
y_true = df['aktual']
y_pred = df['prediksi']

# Hitung confusion matrix
cm = confusion_matrix(y_true, y_pred, labels=[1, 0, 2])  # 1=Negatif, 0=Netral, 2=Positif
print("Confusion Matrix:\n", cm)

# Visualisasi confusion matrix
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negatif', 'Netral', 'Positif'],
            yticklabels=['Negatif', 'Netral', 'Positif'])
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.title('Confusion Matrix')
plt.show()

# Evaluasi klasifikasi (precision, recall, f1-score)
print("\nClassification Report:")
print(classification_report(y_true, y_pred, labels=[1, 0, 2], target_names=['Negatif', 'Netral', 'Positif']))

"""AKURASI SVM"""

import pandas as pd
from sklearn.metrics import accuracy_score

# Baca file CSV hasil prediksi
df = pd.read_csv('DATA_UNTUK_CM.csv')  # ganti dengan nama file kamu

# Ambil label aktual dan prediksi
y_true = df['aktual']
y_pred = df['prediksi']

# Hitung akurasi
accuracy = accuracy_score(y_true, y_pred)

# Tampilkan hasil akurasi
print(f"Akurasi Model SVM: {round(accuracy * 100, 2)}%")

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred, target_names=['Netral', 'Negatif', 'Positif']))

"""#PEMBOBOTAN UNTUK AHP SPK"""

import pandas as pd
import re
from collections import defaultdict

# Load data
data = pd.read_csv('HASIL-PREP.csv', sep=';', on_bad_lines='error', engine='python', encoding='latin-1')

import pandas as pd
import re
import matplotlib.pyplot as plt

# Fungsi untuk menghitung frekuensi kriteria
def calculate_criteria_frequencies(data):
    criteria_counts = {
        'harga': data['Cleaned_Text'].str.count('harga|pulsa|bonus|mahal|murah|biaya|tarif|diskon|hemat|nominal|bayar', flags=re.IGNORECASE).sum(),
        'jangkauan jaringan': data['Cleaned_Text'].str.count('jaringan|sinyal|4g|5g|lemot|stabil|putus|offline|online|kuota|operator|koneksi|akses|internet', flags=re.IGNORECASE).sum(),
        'kecepatan': data['Cleaned_Text'].str.count('cepat|lambat|respon|tunggu|proses|reaksi|responsif|delay|loading|buffering|latensi', flags=re.IGNORECASE).sum(),
        'layanan pelanggan': data['Cleaned_Text'].str.count('layan[an]?|cs|mimin|bantu|bantuan|tolong|dibantu|customer|pelayanan|ramah|solusi|keluhan|komplain|helpdesk|respon', flags=re.IGNORECASE).sum(),
        'fitur tambahan': data['Cleaned_Text'].str.count('fitur|aplikasi|myim|menu|paket|roaming|esim|wa[ ]?im|update|versi|notif|sms|telepon|internet|kuota|promo|bonus', flags=re.IGNORECASE).sum()
    }
    return criteria_counts

# Buat cleaned_text jika belum ada
if 'Cleaned_Text' not in data.columns:
    data['Cleaned_Text'] = data['Stemming'].apply(lambda x: ' '.join(eval(x)) if pd.notnull(x) else '')

# Hitung frekuensi kriteria
criteria_counts = calculate_criteria_frequencies(data)
total = sum(criteria_counts.values())
dynamic_weights = {k: v/total for k, v in criteria_counts.items()}

# Konversi ke DataFrame untuk visualisasi
weights_df = pd.DataFrame({
    'Kriteria': list(dynamic_weights.keys()),
    'Bobot': list(dynamic_weights.values()),
    'Frekuensi': list(criteria_counts.values())
}).sort_values('Bobot', ascending=False)

# Buat visualisasi
plt.figure(figsize=(12, 6))

# Plot frekuensi
plt.subplot(1, 2, 1)
bars1 = plt.bar(weights_df['Kriteria'], weights_df['Frekuensi'], color='skyblue')
plt.title('Frekuensi Kemunculan Kriteria', pad=20)
plt.xlabel('Kriteria')
plt.ylabel('Jumlah Kemunculan')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Tambah label nilai di atas bar
for bar in bars1:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(height)}',
             ha='center', va='bottom')

# Plot bobot
plt.subplot(1, 2, 2)
bars2 = plt.bar(weights_df['Kriteria'], weights_df['Bobot'], color='lightgreen')
plt.title('Bobot Dinamis Kriteria', pad=20)
plt.xlabel('Kriteria')
plt.ylabel('Bobot (0-1)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Tambah label nilai di atas bar (dalam persentase)
for bar in bars2:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.2f}\n({height*100:.1f}%)',
             ha='center', va='bottom')

plt.tight_layout()
plt.show()

# Tampilkan tabel hasil
print("\nTabel Hasil Pembobotan:")
print(weights_df.to_string(index=False))